# Inherit some common Spark stuff
$(call inherit-product, vendor/spark/config/common_full_phone.mk)

# Inherit device stuff
$(call inherit-product, $(LOCAL_PATH)/device.mk)
PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true

PRODUCT_BRAND := OPPO
PRODUCT_DEVICE := CPH2195
PRODUCT_MANUFACTURER := OPPO
PRODUCT_NAME := spark_cph2195
PRODUCT_MODEL := A54 5G


BUILD_FINGERPRINT := OPPO/CPH2195EEA/OP4F39L1:12/SKQ1.210216.001/R.202204071025:user/release-keys

# TODO
# PRODUCT_GMS_CLIENTID_BASE := android-xiaomi
# TARGET_VENDOR_PRODUCT_NAME := laurel_sprout

PRODUCT_BUILD_PROP_OVERRIDES += \
    TARGET_DEVICE="cph2195" \
    PRODUCT_NAME="cph2195" \
    PRIVATE_BUILD_DESC="CPH2195EEA-user 12 SKQ1.210216.001 R.202204071025 release-keys" 

# UDFPS
EXTRA_UDFPS_ICONS := false
EXTRA_UDFPS_ANIMATIONS := false

# Props
SPARK_BUILD_TYPE := UNOFFICIAL
WITH_GAPPS := true
TARGET_BOOT_ANIMATION_RES := 720
TARGET_FACE_UNLOCK_SUPPORTED=true
TARGET_SUPPORTS_GOOGLE_RECORDER := true
TARGET_GAPPS_ARCH := arm64
TARGET_HAS_FOD := false
TARGET_USES_BLUR := true
TARGET_SUPPORTS_QUICK_TAP := true
TARGET_SUPPORTS_ADAPTIVE_CHARGING := true
